version: '3.8'
services:
    apache:
        image: httpd:alpine
        ports:
            - 9999:80
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs/
        networks:
            - default

networks:
    default:
        driver: bridge
